# Generated by Django 4.2 on 2024-09-10 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='vision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='videos.vision'),
        ),
    ]
