# Generated by Django 4.2 on 2024-10-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_invite_vision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='url',
            field=models.URLField(default='', max_length=500, null=True),
        ),
    ]
