# Generated by Django 4.2 on 2024-10-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_alter_vision_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
