# Generated by Django 4.2 on 2024-11-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_vision_rtmp_link_vision_stream_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('uploading', 'Uploading'), ('transcoding', 'Transcoding'), ('draft', 'Draft'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
