# Generated by Django 4.2 on 2024-11-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0017_vision_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('uploading', 'Uploading'), ('transcoding', 'Transcoding'), ('draft', 'Draft'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('live', 'Live'), ('pending_upload', 'Pending Upload'), ('live_failed', 'Live Failed'), ('vod', 'VOD')], default='draft', max_length=20),
        ),
    ]
