# Generated by Django 4.2 on 2024-11-20 12:23

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_birth_date_user_country_user_gender'),
        ('videos', '0019_alter_vision_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='private_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='vision',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
