# Generated by Django 4.2 on 2024-12-31 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_alter_vision_private_user_alter_vision_search_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=500)),
                ('is_local_video', models.BooleanField(default=True)),
                ('question', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='vision',
            name='is_interactive',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StoryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('video_url', models.URLField(max_length=500)),
                ('is_local_video', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_options', to='videos.storynode')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='videos.storynode')),
            ],
        ),
        migrations.AddField(
            model_name='storynode',
            name='vision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_nodes', to='videos.vision'),
        ),
    ]
