# Generated by Django 4.2 on 2025-01-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0021_storynode_vision_is_interactive_storyoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storynode',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready')], default='pending', max_length=10),
        ),
    ]
