# Generated by Django 4.2 on 2025-01-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0022_storynode_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='access_type',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', help_text='Access type for the vision', max_length=10),
        ),
    ]
