# Generated by Django 4.2 on 2025-01-18 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_emailverificationrequest'),
        ('videos', '0023_vision_access_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_vision_requests', to='users.creator')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_requests', to='users.user')),
                ('vision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='videos.vision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visionrequest',
            index=models.Index(fields=['status', 'created_at'], name='videos_visi_status_1edb2d_idx'),
        ),
        migrations.AddIndex(
            model_name='visionrequest',
            index=models.Index(fields=['requester', 'status'], name='videos_visi_request_dc4979_idx'),
        ),
        migrations.AddIndex(
            model_name='visionrequest',
            index=models.Index(fields=['creator', 'status'], name='videos_visi_creator_4f9fdc_idx'),
        ),
    ]
