# Generated by Django 4.2 on 2025-02-02 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0025_vision_vision_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='engagement_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vision',
            name='feature_vector',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vision',
            name='last_recommendation_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vision',
            name='popularity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='VisionSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('engagement_boost', models.FloatField(default=0.0)),
                ('final_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('similar_vision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.vision')),
                ('vision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to='videos.vision')),
            ],
        ),
        migrations.AddIndex(
            model_name='visionsimilarity',
            index=models.Index(fields=['vision', '-final_score'], name='videos_visi_vision__ea4a96_idx'),
        ),
        migrations.AddIndex(
            model_name='visionsimilarity',
            index=models.Index(fields=['similar_vision', '-final_score'], name='videos_visi_similar_65698f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visionsimilarity',
            unique_together={('vision', 'similar_vision')},
        ),
    ]
