# Generated by Django 4.2 on 2025-02-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0027_vision_camera_type_vision_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='ppv_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pay per view price', max_digits=10),
        ),
    ]
