# Generated by Django 4.2 on 2025-02-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0028_vision_ppv_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='story_graph',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
