# Generated by Django 4.2 on 2025-02-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0029_vision_story_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='comment_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='vision',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vision',
            name='live',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='vision',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('uploading', 'Uploading'), ('transcoding', 'Transcoding'), ('draft', 'Draft'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('live', 'Live'), ('pending_upload', 'Pending Upload'), ('live_failed', 'Live Failed'), ('pending_live', 'Pending Live'), ('vod', 'VOD')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='vision',
            index=models.Index(fields=['status', 'created_at'], name='videos_visi_status_062865_idx'),
        ),
        migrations.AddIndex(
            model_name='vision',
            index=models.Index(fields=['live', 'status'], name='videos_visi_live_1033b9_idx'),
        ),
    ]
