# Generated by Django 4.2 on 2025-02-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0030_vision_comment_count_alter_vision_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vision',
            index=models.Index(fields=['status', '-created_at'], name='videos_visi_status_9a0fab_idx'),
        ),
        migrations.AddIndex(
            model_name='vision',
            index=models.Index(fields=['status', 'engagement_score'], name='videos_visi_status_422836_idx'),
        ),
        migrations.AddIndex(
            model_name='vision',
            index=models.Index(fields=['status', 'popularity_score'], name='videos_visi_status_6735dc_idx'),
        ),
        migrations.AddIndex(
            model_name='vision',
            index=models.Index(condition=models.Q(('status', 'vod')), fields=['created_at', 'likes', 'views'], name='vision_active_idx'),
        ),
    ]
