# Generated by Django 4.2 on 2025-02-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0031_vision_videos_visi_status_9a0fab_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='average_rating',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='vision',
            name='latent_factors',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vision',
            name='rating_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='vision',
            index=models.Index(fields=['average_rating', '-created_at'], name='videos_visi_average_7be8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='vision',
            index=models.Index(condition=models.Q(('status', 'vod')), fields=['created_at', 'likes', 'views', 'average_rating'], name='vision_ranking_idx'),
        ),
    ]
