# Generated by Django 4.2 on 2025-02-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0033_remove_vision_videos_visi_average_7be8ac_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnoyIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_binary', models.BinaryField(verbose_name='Binary Annoy index data')),
                ('vision_ids_json', models.TextField(verbose_name='Vision IDs mapping as JSON')),
                ('vector_size', models.IntegerField(verbose_name='Size of the feature vectors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='annoyindex',
            index=models.Index(fields=['-created_at'], name='videos_anno_created_37d5af_idx'),
        ),
    ]
