# Generated by Django 4.2 on 2025-02-24 23:23

import django.contrib.postgres.fields
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0034_annoyindex_annoyindex_videos_anno_created_37d5af_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityComputationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_full_computation', models.DateTimeField(auto_now_add=True)),
                ('last_incremental_update', models.DateTimeField(auto_now_add=True)),
                ('computation_in_progress', models.BooleanField(default=False)),
                ('total_embeddings', models.IntegerField(default=0)),
                ('total_similarities', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('statistics', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
        ),
        migrations.CreateModel(
            name='VisionEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=128)),
                ('embedding_binary', models.BinaryField(blank=True, null=True)),
                ('vector_reduced', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=32)),
                ('vector_size', models.IntegerField(default=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('algorithm_version', models.CharField(default='v1', max_length=50)),
                ('is_stale', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='annoyindex',
            name='videos_anno_created_37d5af_idx',
        ),
        migrations.RemoveIndex(
            model_name='visionsimilarity',
            name='videos_visi_vision__ea4a96_idx',
        ),
        migrations.RemoveIndex(
            model_name='visionsimilarity',
            name='videos_visi_similar_65698f_idx',
        ),
        migrations.RemoveField(
            model_name='annoyindex',
            name='vision_ids_json',
        ),
        migrations.RemoveField(
            model_name='visionsimilarity',
            name='similarity_score',
        ),
        migrations.AddField(
            model_name='annoyindex',
            name='_vision_ids',
            field=models.TextField(blank=True, db_column='vision_ids'),
        ),
        migrations.AddField(
            model_name='annoyindex',
            name='num_trees',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='visionsimilarity',
            name='metadata_similarity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='visionsimilarity',
            name='similarity_factors',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='visionsimilarity',
            name='vector_similarity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='annoyindex',
            name='index_binary',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='annoyindex',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='annoyindex',
            name='vector_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='visionsimilarity',
            name='final_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='visionsimilarity',
            name='similar_vision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='videos.vision'),
        ),
        migrations.AddIndex(
            model_name='annoyindex',
            index=models.Index(fields=['is_current', 'created_at'], name='videos_anno_is_curr_8c1764_idx'),
        ),
        migrations.AddIndex(
            model_name='visionsimilarity',
            index=models.Index(fields=['vision', 'final_score'], name='videos_visi_vision__e03240_idx'),
        ),
        migrations.AddIndex(
            model_name='visionsimilarity',
            index=models.Index(fields=['updated_at'], name='videos_visi_updated_36a0a6_idx'),
        ),
        migrations.AddIndex(
            model_name='visionsimilarity',
            index=models.Index(fields=['vision', 'vector_similarity'], name='videos_visi_vision__ee2de7_idx'),
        ),
        migrations.AddIndex(
            model_name='visionsimilarity',
            index=models.Index(fields=['similar_vision'], name='videos_visi_similar_6d9fd5_idx'),
        ),
        migrations.AddField(
            model_name='visionembedding',
            name='vision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='videos.vision'),
        ),
        migrations.AddIndex(
            model_name='visionembedding',
            index=models.Index(fields=['vision', 'updated_at'], name='videos_visi_vision__722675_idx'),
        ),
        migrations.AddIndex(
            model_name='visionembedding',
            index=models.Index(fields=['is_stale'], name='videos_visi_is_stal_a6a689_idx'),
        ),
        migrations.AddIndex(
            model_name='visionembedding',
            index=models.Index(fields=['algorithm_version'], name='videos_visi_algorit_2485c7_idx'),
        ),
    ]
