# Generated by Django 4.2 on 2025-02-24 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0035_similaritycomputationstate_visionembedding_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimilarityComputationState',
        ),
        migrations.RemoveField(
            model_name='visionembedding',
            name='vision',
        ),
        migrations.RemoveIndex(
            model_name='annoyindex',
            name='videos_anno_is_curr_8c1764_idx',
        ),
        migrations.RemoveIndex(
            model_name='visionsimilarity',
            name='videos_visi_vision__e03240_idx',
        ),
        migrations.RemoveIndex(
            model_name='visionsimilarity',
            name='videos_visi_updated_36a0a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='visionsimilarity',
            name='videos_visi_vision__ee2de7_idx',
        ),
        migrations.RemoveIndex(
            model_name='visionsimilarity',
            name='videos_visi_similar_6d9fd5_idx',
        ),
        migrations.RemoveField(
            model_name='annoyindex',
            name='_vision_ids',
        ),
        migrations.RemoveField(
            model_name='annoyindex',
            name='num_trees',
        ),
        migrations.RemoveField(
            model_name='visionsimilarity',
            name='metadata_similarity',
        ),
        migrations.RemoveField(
            model_name='visionsimilarity',
            name='similarity_factors',
        ),
        migrations.RemoveField(
            model_name='visionsimilarity',
            name='vector_similarity',
        ),
        migrations.AddField(
            model_name='annoyindex',
            name='vision_ids_json',
            field=models.TextField(default=None, verbose_name='Vision IDs mapping as JSON'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visionsimilarity',
            name='similarity_score',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annoyindex',
            name='index_binary',
            field=models.BinaryField(verbose_name='Binary Annoy index data'),
        ),
        migrations.AlterField(
            model_name='annoyindex',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='annoyindex',
            name='vector_size',
            field=models.IntegerField(verbose_name='Size of the feature vectors'),
        ),
        migrations.AlterField(
            model_name='visionsimilarity',
            name='final_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='visionsimilarity',
            name='similar_vision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.vision'),
        ),
        migrations.AddIndex(
            model_name='annoyindex',
            index=models.Index(fields=['-created_at'], name='videos_anno_created_37d5af_idx'),
        ),
        migrations.AddIndex(
            model_name='visionsimilarity',
            index=models.Index(fields=['vision', '-final_score'], name='videos_visi_vision__ea4a96_idx'),
        ),
        migrations.AddIndex(
            model_name='visionsimilarity',
            index=models.Index(fields=['similar_vision', '-final_score'], name='videos_visi_similar_65698f_idx'),
        ),
        migrations.DeleteModel(
            name='VisionEmbedding',
        ),
    ]
