# Generated by Django 4.2 on 2025-03-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0036_delete_similaritycomputationstate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='access_type',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', help_text='Access type for the vision', max_length=50),
        ),
        migrations.AlterField(
            model_name='vision',
            name='camera_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('external', 'External'), ('none', 'None')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='visionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
