# Generated by Django 4.2 on 2025-03-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0037_alter_vision_access_type_alter_vision_camera_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('uploading', 'Uploading'), ('transcoding', 'Transcoding'), ('draft', 'Draft'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('live', 'Live'), ('pending_upload', 'Pending Upload'), ('live_failed', 'Live Failed'), ('pending_live', 'Pending Live'), ('vod', 'VOD'), ('processing', 'Processing')], db_index=True, default='draft', max_length=20),
        ),
    ]
