# Generated by Django 4.2 on 2025-03-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0039_vision_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='duration',
            field=models.FloatField(blank=True, help_text='Duration of the video in seconds', null=True),
        ),
    ]
