# Generated by Django 4.2 on 2025-03-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0040_vision_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='duration',
            field=models.BigIntegerField(blank=True, help_text='Duration of the video in milliseconds', null=True),
        ),
    ]
