# Generated by Django 4.2 on 2024-10-08 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_thumbnail'),
        ('videos', '0013_alter_vision_url'),
        ('users', '0016_badge_userbadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('PENDING', 'Pending'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('host_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_collab_invites', to='users.creator')),
                ('invited_creators', models.ManyToManyField(related_name='received_collab_invites', to='users.creator')),
                ('vision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.vision')),
            ],
        ),
        migrations.AddConstraint(
            model_name='collabinvite',
            constraint=models.CheckConstraint(check=models.Q(('event__isnull', False), ('vision__isnull', False), _connector='OR'), name='collab_invite_event_or_vision'),
        ),
    ]
