# Generated by Django 4.2 on 2024-10-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_activityevent_notificationtemplate_useractivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabinvite',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
