# Generated by Django 4.2 on 2024-10-17 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_remove_vision_is_live'),
        ('users', '0020_user_blocked_users_user_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('vision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.vision')),
            ],
            options={
                'ordering': ['-watched_at'],
                'unique_together': {('user', 'vision')},
            },
        ),
    ]
