# Generated by Django 4.2 on 2024-10-17 08:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_watchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('TECHNICAL', 'Technical Issue'), ('ACCOUNT', 'Account Issue'), ('BILLING', 'Billing Issue'), ('FEATURE', 'Feature Request'), ('OTHER', 'Other')], max_length=20)),
                ('additional_info', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
