# Generated by Django 4.2 on 2025-01-17 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signincoderequest',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
