# Generated by Django 4.2 on 2025-01-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_user_ban_reason_user_banned_at_user_banned_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='available_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='creator',
            name='can_receive_payments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creator',
            name='monetization_status',
            field=models.CharField(choices=[('pending', 'Pending Setup'), ('onboarding', 'Connect Onboarding'), ('active', 'Active'), ('disabled', 'Disabled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='creator',
            name='stripe_connect_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='stripe_connect_onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creator',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
