# Generated by Django 4.2 on 2025-01-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_creator_available_earnings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='available_earnings',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='total_earnings',
        ),
    ]
