# Generated by Django 4.2 on 2025-02-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0028_vision_ppv_price'),
        ('users', '0032_user_notify_comment_replies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectator',
            name='ppv_visions',
            field=models.ManyToManyField(blank=True, related_name='ppv_purchased_by', to='videos.vision'),
        ),
    ]
