# Generated by Django 4.2 on 2025-02-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_spectator_ppv_visions'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectator',
            name='reminder_creators',
            field=models.ManyToManyField(blank=True, related_name='reminded_by', to='users.creator'),
        ),
    ]
