# Generated by Django 4.2 on 2025-03-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_spectator_reminder_creators'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='revenuecat_uuid',
            field=models.CharField(blank=True, help_text='Unique identifier for this user in RevenueCat', max_length=100, null=True, unique=True),
        ),
    ]
