# Generated by Django 4.2 on 2025-03-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_user_revenuecat_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='issue_type',
            field=models.CharField(choices=[('TECHNICAL', 'Technical Issue'), ('ACCOUNT', 'Account Issue'), ('BILLING', 'Billing Issue'), ('FEATURE', 'Feature Request'), ('OTHER', 'Other')], max_length=100),
        ),
    ]
