# Generated by Django 4.2 on 2025-03-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0039_vision_dislikes'),
        ('users', '0038_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectator',
            name='disliked_visions',
            field=models.ManyToManyField(blank=True, related_name='disliked_by', to='videos.vision'),
        ),
    ]
