# Generated by Django 4.2 on 2025-03-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_spectator_disliked_visions'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='view_duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
