# Generated by Django 4.2 on 2025-03-23 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0041_alter_vision_duration'),
        ('users', '0040_watchhistory_ip_address_watchhistory_view_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('view_duration', models.PositiveIntegerField(default=0)),
                ('is_valid', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('vision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.vision')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='viewcount',
            index=models.Index(fields=['user', 'timestamp'], name='users_viewc_user_id_1f095f_idx'),
        ),
        migrations.AddIndex(
            model_name='viewcount',
            index=models.Index(fields=['vision', 'timestamp'], name='users_viewc_vision__a99bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='viewcount',
            index=models.Index(fields=['ip_address', 'timestamp'], name='users_viewc_ip_addr_7fd551_idx'),
        ),
    ]
