# Generated by Django 4.2 on 2024-10-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='description',
        ),
        migrations.AddField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='promotion_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(choices=[('discount', 'Discount'), ('free_trial', 'Free Trial')], default='discount', max_length=20),
        ),
        migrations.AddField(
            model_name='promotion',
            name='redemption_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
