# Generated by Django 4.2 on 2025-02-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_subscription_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='stripe_coupon_id',
        ),
        migrations.AddField(
            model_name='promotion',
            name='redemption_count',
            field=models.IntegerField(default=0),
        ),
    ]
