# Generated by Django 4.2 on 2025-03-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_subscription_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_subscription_item_id',
        ),
    ]
