# Generated by Django 4.2 on 2025-01-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notification_rule_arn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='stream_start_rule_arn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
