# Generated by Django 4.2 on 2025-01-11 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_notification_rule_arn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='stream_start_rule_arn',
        ),
    ]
