# Generated by Django 4.2 on 2025-01-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
