# Generated by Django 4.2 on 2025-02-02 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('engagement_boost', models.FloatField(default=0.0)),
                ('final_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='engagement_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='event',
            name='feature_vector',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='last_recommendation_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='popularity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time'], name='events_even_start_t_c2d277_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['popularity_score'], name='events_even_popular_146e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['engagement_score'], name='events_even_engagem_14316e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['creator', 'start_time'], name='events_even_creator_bbe5ef_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['last_recommendation_update'], name='events_even_last_re_037c73_idx'),
        ),
        migrations.AddField(
            model_name='eventsimilarity',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventsimilarity',
            name='similar_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddIndex(
            model_name='eventsimilarity',
            index=models.Index(fields=['event', '-final_score'], name='events_even_event_i_fbcc95_idx'),
        ),
        migrations.AddIndex(
            model_name='eventsimilarity',
            index=models.Index(fields=['similar_event', '-final_score'], name='events_even_similar_59a3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='eventsimilarity',
            index=models.Index(fields=['created_at'], name='events_even_created_ed9c79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventsimilarity',
            unique_together={('event', 'similar_event')},
        ),
    ]
