# Generated by Django 4.2 on 2025-02-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventsimilarity_event_engagement_score_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-start_time'], name='events_even_start_t_33fd3e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['creator', '-engagement_score'], name='events_even_creator_bf0577_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['creator', 'vision'], name='events_even_creator_f089f6_idx'),
        ),
    ]
