# Generated by Django 4.2 on 2025-02-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_events_even_start_t_33fd3e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAnnoyIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_binary', models.BinaryField()),
                ('event_ids', models.JSONField()),
                ('vector_size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='eventannoyindex',
            index=models.Index(fields=['-created_at'], name='events_even_created_ebb93b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventannoyindex',
            index=models.Index(fields=['is_current'], name='events_even_is_curr_ffc10a_idx'),
        ),
    ]
