# Generated by Django 4.2 on 2024-10-08 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
