# Generated by Django 4.2 on 2025-01-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_transaction_options_remove_tip_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='platform_fee',
        ),
    ]
