# Generated by Django 4.2 on 2025-02-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_creditbalance_subscriptiontier_usersubscription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditbalance',
            old_name='balance',
            new_name='creator_balance',
        ),
        migrations.AddField(
            model_name='creditbalance',
            name='spectator_balance',
            field=models.IntegerField(default=0),
        ),
    ]
