# Generated by Django 4.2 on 2025-02-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_rename_balance_creditbalance_creator_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('subscription', 'Subscription'), ('tip', 'Tip'), ('refund', 'Refund'), ('vision_request', 'Vision Request')], max_length=50),
        ),
    ]
