# Generated by Django 4.2 on 2025-03-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_credittransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='cancel_reason',
            field=models.CharField(blank=True, help_text='Reason for cancellation if provided by RevenueCat', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Whether this subscription is in a trial period'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('subscription', 'Subscription'), ('tip', 'Tip'), ('refund', 'Refund'), ('vision_request', 'Vision Request'), ('one_time_purchase', 'One-time Purchase'), ('tier_change', 'Subscription Tier Change')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('paused', 'Paused'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='active', max_length=20),
        ),
    ]
