# Generated by Django 4.2 on 2025-03-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_usersubscription_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='credits_per_month',
            field=models.IntegerField(default=0, help_text='Number of credits received per month'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='product_id',
            field=models.CharField(blank=True, help_text='RevenueCat product ID in format subscription_monthly_{credits}', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.subscriptiontier'),
        ),
    ]
