# Generated by Django 4.2 on 2025-03-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_processedrevenuecatevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('subscription', 'Subscription'), ('tip', 'Tip'), ('refund', 'Refund'), ('vision_request', 'Vision Request'), ('one_time_purchase', 'One-time Purchase'), ('tier_change', 'Subscription Tier Change'), ('topup', 'Credit Top-up')], max_length=50),
        ),
    ]
