# Generated by Django 4.2 on 2025-03-01 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_credittransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='tier',
            field=models.ForeignKey(blank=True, help_text='Legacy field - no longer used. Use product_id instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.usersubscription'),
        ),
        migrations.DeleteModel(
            name='SubscriptionTier',
        ),
    ]
