# Generated by Django 4.2 on 2025-03-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_usersubscription_tier_delete_subscriptiontier'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='has_pending_change',
            field=models.BooleanField(default=False, help_text='Whether this subscription has a pending change (e.g. downgrade)'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='pending_change_date',
            field=models.DateTimeField(blank=True, help_text='Date when pending change will take effect', null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='pending_product_id',
            field=models.CharField(blank=True, help_text='Product ID that will take effect at renewal', max_length=255, null=True),
        ),
    ]
