# Generated by Django 4.2 on 2025-03-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_usersubscription_has_pending_change_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='unique_active_subscription_per_user'),
        ),
    ]
