# Generated by Django 4.2 on 2025-03-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_usersubscription_unique_active_subscription_per_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usersubscription',
            name='unique_active_subscription_per_user',
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_subscription_per_user'),
        ),
    ]
