# Generated by Django 4.2 on 2025-03-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_remove_usersubscription_unique_active_subscription_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditbalance',
            name='topup_balance',
            field=models.IntegerField(default=0),
        ),
    ]
