# Generated by Django 4.2 on 2025-03-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_creditbalance_topup_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditbalance',
            name='topup_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
