# Generated by Django 4.2 on 2025-03-08 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0038_alter_vision_status'),
        ('payments', '0020_alter_credittransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='vision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips', to='videos.vision'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('subscription', 'Subscription'), ('credit_subscription', 'Credit Subscription'), ('tip', 'Tip'), ('refund', 'Refund'), ('vision_request', 'Vision Request'), ('one_time_purchase', 'One-time Purchase'), ('tier_change', 'Subscription Tier Change'), ('topup', 'Credit Top-up'), ('subscription_renewal', 'Subscription Renewal')], max_length=50),
        ),
    ]
